name: Build and Test with Gulp
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.3.0
        with:
          node-version: '20.x'  # Specify your Node.js version
          cache: 'npm'          # Cache npm dependencies
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci  # Use npm ci for cleaner, reproducible installs

      - name: Run Gulp build
        run: npx gulp build  # Replace 'build' with your Gulp task name

      - name: Run tests (if applicable)
        run: npx gulp test   # Replace 'test' with your Gulp test task, if any
