name: Build and Test with Gulp

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.3.0
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Verify package.json
        run: |
          cat package.json | jq . || (echo "Invalid JSON in package.json"; cat -n package.json | grep -C 5 '^ *34'; exit 1)
          echo "package.json is valid"

      - name: List source files
        run: ls -R src/ || echo "No src/ folder found"

      - name: Install dependencies
        run: npm ci

      - name: Run Gulp build
        run: npx gulp build --verbose

      - name: Run Vite build
        run: npm run build  # Run Vite to bundle React app

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/
          retention-days: 7
